{{- if .Values.rabbitmq.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chart.componentname" (list . "clusters") }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: prometheus
      interval: {{ .Values.rabbitmq.serviceMonitor.interval }}
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
  namespaceSelector:
    any: true
{{- end }}
